export default {

    otazky: [

        // 0.místnost - pravidla
        { 
            id: 0,
            uvitani: '<p><strong>Vítej učedníku</strong> na dobrodružné cestě do našeho podzemí! Ovšem pozor, slávy a bohatství u nás nedosáhneš mečem či kouzlem, ale svými <strong>vědomostmi!</strong></p> <p>V každé místnosti, kterou navštívíš, tě bude čekat místní obyvatel s otázkou, která ho moc trápí. <strong>Když správně odpovíš, odmění tě zlaťákem, ovšem když se spleteš, nejspíš tě vezme něčím po hlavě</strong> a to trochu zabolí! Dostaneš se k němu jednoduše pomocí <strong>šipek na klávesnici</strong>. Některé místnosti jsou trochu záludné a asi se trochu projdeš.</p> <p>Tak hodně zdaru a <strong>vzhůru dolů do podzemí!</strong></p>',
        },
        // 1.místnost - kuchyně
        { 
            id: 1,
            uvitani: '"To jsem rád, že tě vidím! Určitě mi pomůžeš s receptem. Takže, potřebuji zjistit, ',
            otazka: 'která z těchto hub je nejedlá:"',
            odpovedi: [
                'hřib smrkový',
                'bedla obecná',
                'hřib satan',
            ],
            spravna: 2,
            reakceYes: '"Skvělé! To bude super bašta pro celé podzemí! Díky za pomoc."',
            reakceNo: '"Mno, raději se podívám do kuchařky, to se mi nezdá,… hmmm…, že ty chceš, aby nám bylo všem špatně?!? Mazej pryč, než tě vezmu válečkem!"',
        },
        { 
            id: 2,
            uvitani: '"To jsem rád, že tě vidím! Určitě mi pomůžeš s receptem. Takže, potřebuji zjistit, ',
            otazka: 'ze kterého zvířete mohu použít vajíčko do smaženice:"',
            odpovedi: [
                'kohout',
                'slepice',
                'netopýr',
            ],
            spravna: 1,
            reakceYes: '"Skvělé! To bude super bašta pro celé podzemí! Díky za pomoc."',
            reakceNo: '"Mno, raději se podívám do kuchařky, to se mi nezdá,… hmmm…, že ty chceš, aby nám bylo všem špatně?!? Mazej pryč, než tě vezmu válečkem!"',
        },
        { 
            id: 3,
            uvitani: '"To jsem rád, že tě vidím! Určitě mi pomůžeš s receptem. Takže, potřebuji zjistit, ',
            otazka: 'které z těchto jídel není ovoce:"',
            odpovedi: [
                'jablko',
                'meloun',
                'ananas',
            ],
            spravna: 1,
            reakceYes: '"Skvělé! To bude super bašta pro celé podzemí! Díky za pomoc."',
            reakceNo: '"Mno, raději se podívám do kuchařky, to se mi nezdá,… hmmm…, že ty chceš, aby nám bylo všem špatně?!? Mazej pryč, než tě vezmu válečkem!"',
        },
        { 
            id: 4,
            uvitani: '"To jsem rád, že tě vidím! Určitě mi pomůžeš s receptem. Takže, potřebuji zjistit, ',
            otazka: 'které koření vypadá jako hvězdička:"',
            odpovedi: [
                'badyán',
                'skořice',
                'hřebíček',
            ],
            spravna: 0,
            reakceYes: '"Skvělé! To bude super bašta pro celé podzemí! Díky za pomoc."',
            reakceNo: '"Mno, raději se podívám do kuchařky, to se mi nezdá,… hmmm…, že ty chceš, aby nám bylo všem špatně?!? Mazej pryč, než tě vezmu válečkem!"',
        },
        { 
            id: 5,
            uvitani: '"To jsem rád, že tě vidím! Určitě mi pomůžeš s receptem. Takže, potřebuji zjistit, ',
            otazka: 'ze kterého zvířete je hovězí maso:"',
            odpovedi: [
                'krůta',
                'prase',
                'kráva',
            ],
            spravna: 2,
            reakceYes: '"Skvělé! To bude super bašta pro celé podzemí! Díky za pomoc."',
            reakceNo: '"Mno, raději se podívám do kuchařky, to se mi nezdá,… hmmm…, že ty chceš, aby nám bylo všem špatně?!? Mazej pryč, než tě vezmu válečkem!"',
        },
        // 2.místnost - knihovna
        { 
            id: 6,
            uvitani: '"Zatracení šotci! Vytrhali a rozstříhali stránky z knížek! Co mám teď krucipísek dělat? Ach, ty to budeš vědět! ',
            otazka: 'Která z těchto pohádek nepatří do pohádek Hanse Christiana Andersena?"',
            odpovedi: [
                'Malá mořská víla',
                'Ošklivé káčátko',
                'Popelka',
            ],
            spravna: 2,
            reakceYes: '"Ty jsi velmi sečtělý, jen tak dál. Víš, že: „Ten, kdo čte, žije s každou další knihou život navíc. Kdo nečte, má jen ten svůj" - Oscar Wilde."',
            reakceNo: '"No, co jsem mohl čekat! Dnešní mládež vůbec nečte! Zmiz mi raději z očí!"',
        },
        { 
            id: 7,
            uvitani: '"Zatracení šotci! Vytrhali a rozstříhali stránky z knížek! Co mám teď krucipísek dělat? Ach, ty to budeš vědět! ',
            otazka: 'Které z těchto slov je špatně napsané:"',
            odpovedi: [
                'slyšet',
                'výskat',
                'lyška',
            ],
            spravna: 2,
            reakceYes: '"Ty jsi velmi sečtělý, jen tak dál. Víš, že: „Ten, kdo čte, žije s každou další knihou život navíc. Kdo nečte, má jen ten svůj" - Oscar Wilde."',
            reakceNo: '"No, co jsem mohl čekat! Dnešní mládež vůbec nečte! Zmiz mi raději z očí!"',
        },
        { 
            id: 8,
            uvitani: '"Zatracení šotci! Vytrhali a rozstříhali stránky z knížek! Co mám teď krucipísek dělat? Ach, ty to budeš vědět! ',
            otazka: 'Kdo napsal Povídání o pejskovi a kočičce?"',
            odpovedi: [
                'Karel Čapek',
                'Josef Čapek',
                'Zdeněk Müller',
            ],
            spravna: 1,
            reakceYes: '"Ty jsi velmi sečtělý, jen tak dál. Víš, že: „Ten, kdo čte, žije s každou další knihou život navíc. Kdo nečte, má jen ten svůj" - Oscar Wilde."',
            reakceNo: '"No, co jsem mohl čekat! Dnešní mládež vůbec nečte! Zmiz mi raději z očí!"',
        },
        { 
            id: 9,
            uvitani: '"Zatracení šotci! Vytrhali a rozstříhali stránky z knížek! Co mám teď krucipísek dělat? Ach, ty to budeš vědět! ',
            otazka: 'Jak se jmenuje slavná trojce z knihy Harry Potter?"',
            odpovedi: [
                'Harry, Rober, Heřmana',
                'Harry, Ren, Hana',
                'Harry, Ron, Hermiona',
            ],
            spravna: 2,
            reakceYes: '"Ty jsi velmi sečtělý, jen tak dál. Víš, že: „Ten, kdo čte, žije s každou další knihou život navíc. Kdo nečte, má jen ten svůj" - Oscar Wilde."',
            reakceNo: '"No, co jsem mohl čekat! Dnešní mládež vůbec nečte! Zmiz mi raději z očí!"',
        },
        { 
            id: 10,
            uvitani: '"Zatracení šotci! Vytrhali a rozstříhali stránky z knížek! Co mám teď krucipísek dělat? Ach, ty to budeš vědět! ',
            otazka: 'Které slovo je správně napsané:"',
            odpovedi: [
                'pomněnka',
                'zapoměl',
                'doměnka',
            ],
            spravna: 0,
            reakceYes: '"Ty jsi velmi sečtělý, jen tak dál. Víš, že: „Ten, kdo čte, žije s každou další knihou život navíc. Kdo nečte, má jen ten svůj" - Oscar Wilde."',
            reakceNo: '"No, co jsem mohl čekat! Dnešní mládež vůbec nečte! Zmiz mi raději z očí!"',
        },
        // 3.místnost - posilovna
        { 
            id: 11,
            uvitani: '"5, 6, 7... Ehm... teda 98, 99, 100! Uff, takové svaly budeš mít jednou taky, ale není důležité trénovat jen tělo, ale i mozek! Schválně, jestli budeš znát odpověď... ',
            otazka: 'Znáš naši nejznámější rychlobruslařku?"',
            odpovedi: [
                'Gabriela Koukalová',
                'Ester Ledecká',
                'Martina Sáblíková',
            ],
            spravna: 2,
            reakceYes: '"To není vůbec špatné... Možná si tě najmu do svého vojska. Válečník musí být silný i chytrý!"',
            reakceNo: '"Ty bys mi nebyl moc platný... Radši jdi, než si z tebe udělám boxovací pytel!"',
        },
        { 
            id: 12,
            uvitani: '"5, 6, 7... Ehm... teda 98, 99, 100! Uff, takové svaly budeš mít jednou taky, ale není důležité trénovat jen tělo, ale i mozek! Schválně, jestli budeš znát odpověď... ',
            otazka: 'Jaké barvy mají olympijské kruhy:"',
            odpovedi: [
                'červená, modrá, žlutá, zelená, černá',
                'modrá, červená, fialová, černá, žlutá',
                'zelená, hnědá, žlutá, modrá, červená',
            ],
            spravna: 0,
            reakceYes: '"To není vůbec špatné... Možná si tě najmu do svého vojska. Válečník musí být silný i chytrý!"',
            reakceNo: '"Ty bys mi nebyl moc platný... Radši jdi, než si z tebe udělám boxovací pytel!"',
        },
        { 
            id: 13,
            uvitani: '"5, 6, 7... Ehm... teda 98, 99, 100! Uff, takové svaly budeš mít jednou taky, ale není důležité trénovat jen tělo, ale i mozek! Schválně, jestli budeš znát odpověď... ',
            otazka: 'V Brně hraje známý hokejový tým - tušíš, jak se jmenuje?"',
            odpovedi: [
                'HC Oceláři',
                'HC Sparta',
                'HC Kometa',
            ],
            spravna: 2,
            reakceYes: '"To není vůbec špatné... Možná si tě najmu do svého vojska. Válečník musí být silný i chytrý!"',
            reakceNo: '"Ty bys mi nebyl moc platný... Radši jdi, než si z tebe udělám boxovací pytel!"',
        },
        { 
            id: 14,
            uvitani: '"5, 6, 7... Ehm... teda 98, 99, 100! Uff, takové svaly budeš mít jednou taky, ale není důležité trénovat jen tělo, ale i mozek! Schválně, jestli budeš znát odpověď... ',
            otazka: 'Jaká disciplína nepatří do atletiky:"',
            odpovedi: [
                'skok do dálky',
                'plavání',
                'hod oštěpem',
            ],
            spravna: 1,
            reakceYes: '"To není vůbec špatné... Možná si tě najmu do svého vojska. Válečník musí být silný i chytrý!"',
            reakceNo: '"Ty bys mi nebyl moc platný... Radši jdi, než si z tebe udělám boxovací pytel!"',
        },
        { 
            id: 15,
            uvitani: '"5, 6, 7... Ehm... teda 98, 99, 100! Uff, takové svaly budeš mít jednou taky, ale není důležité trénovat jen tělo, ale i mozek! Schválně, jestli budeš znát odpověď... ',
            otazka: 'Víš jaký sport dělá Ester Ledecká?"',
            odpovedi: [
                'Snowboard a alpské lyže',
                'Skok do dálky a běh',
                'Rychlobruslení',
            ],
            spravna: 0,
            reakceYes: '"To není vůbec špatné... Možná si tě najmu do svého vojska. Válečník musí být silný i chytrý!"',
            reakceNo: '"Ty bys mi nebyl moc platný... Radši jdi, než si z tebe udělám boxovací pytel!"',
        },
        // 4.místnost - kartograf
        { 
            id: 16,
            uvitani: '"Vítej, jistě ti nebude vadit, když si tě trochu prozkouším. Tak schválně, dokážeš mi říct, ',
            otazka: 'kde pramení Vltava?"',
            odpovedi: [
                'Šumava',
                'Českomoravská vysočina',
                'Orlické hory',
            ],
            spravna: 0,
            reakceYes: '"No výborně! Vidím, že jsi velký cestovatel. Tak šťastnou cestu!"',
            reakceNo: '"Raději běž dál, moc jsi toho ještě neprocestoval ani na mapě jak vidím."',
        },
        { 
            id: 17,
            uvitani: '"Vítej, jistě ti nebude vadit, když si tě trochu prozkouším. Tak schválně, dokážeš mi říct, ',
            otazka: 'jaká je nejvyšší hora Jeseníků?"',
            odpovedi: [
                'Lysá hora',
                'Praděd',
                'Keprník',
            ],
            spravna: 1,
            reakceYes: '"No výborně! Vidím, že jsi velký cestovatel. Tak šťastnou cestu!"',
            reakceNo: '"Raději běž dál, moc jsi toho ještě neprocestoval ani na mapě jak vidím."',
        },
        { 
            id: 18,
            uvitani: '"Vítej, jistě ti nebude vadit, když si tě trochu prozkouším. Tak schválně, dokážeš mi říct, ',
            otazka: 'která řeka ústí do moře?"',
            odpovedi: [
                'Labe',
                'Vltava',
                'Morava',
            ],
            spravna: 0,
            reakceYes: '"No výborně! Vidím, že jsi velký cestovatel. Tak šťastnou cestu!"',
            reakceNo: '"Raději běž dál, moc jsi toho ještě neprocestoval ani na mapě jak vidím."',
        },
        { 
            id: 19,
            uvitani: '"Vítej, jistě ti nebude vadit, když si tě trochu prozkouším. Tak schválně, dokážeš mi říct, ',
            otazka: 'jaké je hlavní město Austrálie"',
            odpovedi: [
                'Sydney',
                'Melbourne',
                'Canberra',
            ],
            spravna: 2,
            reakceYes: '"No výborně! Vidím, že jsi velký cestovatel. Tak šťastnou cestu!"',
            reakceNo: '"Raději běž dál, moc jsi toho ještě neprocestoval ani na mapě jak vidím."',
        },
        { 
            id: 20,
            uvitani: '"Vítej, jistě ti nebude vadit, když si tě trochu prozkouším. Tak schválně, dokážeš mi říct, ',
            otazka: 's kým sousedí Česká republika?"',
            odpovedi: [
                'Německo, Polsko, Slovensko, Ukrajina',
                'Polsko, Rakousko, Švýcarsko, Slovensko',
                'Slovensko, Německo, Rakousko, Polsko',
            ],
            spravna: 2,
            reakceYes: '"No výborně! Vidím, že jsi velký cestovatel. Tak šťastnou cestu!"',
            reakceNo: '"Raději běž dál, moc jsi toho ještě neprocestoval ani na mapě jak vidím."',
        },
        // 5.místnost - alchymista
        { 
            id: 21,
            uvitani: '"Vítej vítej, jistě ti nebude vadit, když si tě trochu prozkouším. Tak schválně, dokážeš mi říct, ',
            otazka: 'kdo objevil Radium?"',
            odpovedi: [
                'Albert Einstein',
                'Marie Curie-Skłodowská',
                'Stephen Hawking',
            ],
            spravna: 1,
            reakceYes: '"Skvělé! Dost by se mi hodil učedník, co by mi nosil lektvary, popřemýšlej o tom."',
            reakceNo: '"No jej! Ty to tu chceš vyhodit celé do povětří! Raději se odsud rychle kliď!"',
        },
        { 
            id: 22,
            uvitani: '"Vítej vítej, jistě ti nebude vadit, když si tě trochu prozkouším. Tak schválně, dokážeš mi říct, ',
            otazka: 'z čeho se skládá atom?"',
            odpovedi: [
                'Z jádra a obalu',
                'Z pecky a obalu',
                'Jen z jádra',
            ],
            spravna: 0,
            reakceYes: '"Skvělé! Dost by se mi hodil učedník, co by mi nosil lektvary, popřemýšlej o tom."',
            reakceNo: '"No jej! Ty to tu chceš vyhodit celé do povětří! Raději se odsud rychle kliď!"',
        },
        { 
            id: 23,
            uvitani: '"Vítej vítej, jistě ti nebude vadit, když si tě trochu prozkouším. Tak schválně, dokážeš mi říct, ',
            otazka: 'jaká je chemická značka zlata?"',
            odpovedi: [
                'Al',
                'Br',
                'Au',
            ],
            spravna: 2,
            reakceYes: '"Skvělé! Dost by se mi hodil učedník, co by mi nosil lektvary, popřemýšlej o tom."',
            reakceNo: '"No jej! Ty to tu chceš vyhodit celé do povětří! Raději se odsud rychle kliď!"',
        },
        { 
            id: 24,
            uvitani: '"Vítej vítej, jistě ti nebude vadit, když si tě trochu prozkouším. Tak schválně, dokážeš mi říct, ',
            otazka: 'kdo vynalezl telefon?"',
            odpovedi: [
                'Thomas Alva Edison',
                'Alexander Graham Bell',
                'Nikola Tesla',
            ],
            spravna: 1,
            reakceYes: '"Skvělé! Dost by se mi hodil učedník, co by mi nosil lektvary, popřemýšlej o tom."',
            reakceNo: '"No jej! Ty to tu chceš vyhodit celé do povětří! Raději se odsud rychle kliď!"',
        },
        { 
            id: 25,
            uvitani: '"Vítej vítej, jistě ti nebude vadit, když si tě trochu prozkouším. Tak schválně, dokážeš mi říct, ',
            otazka: 'která planeta je největší?"',
            odpovedi: [
                'Merkur',
                'Slunce',
                'Jupiter',
            ],
            spravna: 2,
            reakceYes: '"Skvělé! Dost by se mi hodil učedník, co by mi nosil lektvary, popřemýšlej o tom."',
            reakceNo: '"No jej! Ty to tu chceš vyhodit celé do povětří! Raději se odsud rychle kliď!"',
        },
        // přidány další místnosti - možnost dalšího rozšíření...
        // místnost - prohra
        { 
            id: 26,
            uvitani: 'KONEC HRY',
            hodnoceni: 'Je mi líto, ale chce to dávat ve škole větší pozor. Ale nezoufej, můžeš to zkusit znovu, stačí kliknout na tlačítko... Přeji ti, ať se příště vede lépe!',
        },
        // místnost - výhra
        { 
            id: 27,
            uvitani: 'Hurááá! Máš za sebou úspěšný průchod KOBKAMA VĚDĚNÍ! Gratuluji!',
            nazev: 'Získal jsi: 1 penízek',
            hodnoceni: 'Tvoje hodnost: Pasáček vepřů',
            popis: 'No, něco jsi věděl, ale žádná sláva to nebyla. Pokud to nezlepšíš, můžeš leda tak pást vepře. Život to není moc voňavý, ale zase je to práce ve stále mladém a dynamickém kolektivu!', 
        },
        {
            id: 28,
            uvitani: 'Hurááá! Máš za sebou úspěšný průchod KOBKAMA VĚDĚNÍ! Gratulujeme!',
            nazev: 'Získal jsi: 2 penízky',
            hodnoceni: 'Tvoje hodnost: Zbrojnoš',
            popis: 'No hele, podívej, …řadový zbrojnoš nemusí být úplná bedna, přeci jen nasazování Španělských botiček na povozy není zas až tak náročné. Ale taky nemůže být úplný prosťáček, aby ho každý ošálil a utekl mu lecjaký zloduch, co se pokouší přijít do království ukrást princeznu nebo uhranout nějakou tu krávu. Nebo naopak. Mohlo by to být lepší, ale dva bodíky tě dostanou alespoň na tuto příčku.',
        },
        {    
            id: 29,
            uvitani: 'Hurááá! Máš za sebou úspěšný průchod KOBKAMA VĚDĚNÍ! Gratulujeme!',
            nazev: 'Získal jsi 3 penízky',
            hodnoceni: 'Tvoje hodnost: Kupec',
            popis: 'Povolání kupce je trochu adrenalinový sport. Kde kdo se vás snaží oškubat a to jak ze zákazníků, tak od vrchnosti, a vy se musíte hodně otáčet, abyste neskončili chudí jako kostelní myš. Dobrý kupec musí být bystré mysli (nikoliv však Müsli) a orientovat se alespoň trochu v kde čem, aby mohl také s kde čím obchodovat. Teď už jen kde ten “Kdečem” sehnat a dobře na něm vydělat.',
        },
        {    
            id: 30,
            uvitani: 'Hurááá! Máš za sebou úspěšný průchod KOBKAMA VĚDĚNÍ! Gratulujeme!',
            nazev: 'Získal jsi 4 penízky',
            hodnoceni: 'Tvoje hodnost: Rytíř',
            popis: 'Rytíř je velice odpovědná funkce. Kde kdo si jej představí jen jako přerostlou plechovku od guláše, co někde máchá mečem. To však není úplně pravda. Rytíř je královým prvním mužem, který nejen bojuje, ale obrací se na něj i královští poddaní, aby je (třeba zrušit) rozsoudil nebo jim všelijak pomohl. A on by se toho měl pro krále zhostit, a to se ctí! Kdyby ne, mohl by taky skončit jak dlouhý, tak široký ve sběrných surovinách. Ale to tebe nečeká. Chyběl ti jen malý krůček k nejlepšímu výsledku, takže se s klidem můžeš počítat mezi vážené rytíře šišatého stolu. A to už něco znamená!',
        },
        {    
            id: 31,
            uvitani: 'Hurááá! Máš za sebou úspěšný průchod KOBKAMA VĚDĚNÍ! Gratulujeme!',
            nazev: 'Získal jsi 5 penízků',
            hodnoceni: 'Tvoje hodnost: Král',
            popis: 'Lepší už to být prostě nemůže. Král musí být moudrý, silný a znalý mnoha oborů, aby mohl svému království dobře vládnout. To vše jsi právě prokázal. Je vidět, že tě jen tak někdo nenachytá na švestkách a nemůže tě vodit za nos. Výborně! Ať žije král!',
        },
        
    ],

};
